version: '3.8'

services:
  mosquitto:
    build: ./mosquitto
    ports:
      - 1883:1883

  jobmanager:
    image: flink:1.13
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        jobmanager.memory.flink.size: 2048mb
        jobmanager.memory.process.size: 3072mb
       # state.backend: rocksdb
       # state.backend.incremental: true
       # state.checkpoints.dir: file:///checkpoint-dir/
       # state.backend: hashmap
       # state.checkpoints.dir: file:///checkpoint-dir/
       # state.storage.fs.memory-threshold: 1 mb
       # state.backend: rocksdb
       # state.backend.incremental: true
       # state.checkpoints.dir: hdfs:///flink-checkpoints
       # jobmanager.memory.flink.size: 2048mb
       # jobmanager.memory.process.size: 3072mb
  taskmanager:
    image: flink:1.13
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
        taskmanager.memory.flink.size: 2048mb
        taskmanager.memory.process.size: 3072mb
       # state.backend: rocksdb
       # state.backend.incremental: true
       # state.checkpoints.dir: file:///checkpoint-dir/
       # state.backend: hashmap
       # state.checkpoints.dir: file:///checkpoint-dir/
       # state.storage.fs.memory-threshold: 1 mb
       # state.backend: rocksdb
       # state.backend.incremental: true
       # state.checkpoints.dir: hdfs:///flink-checkpoints
       # taskmanager.memory.flink.size: 2048mb
       # taskmanager.memory.process.size: 3072mb

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    restart: always
    ports:
      - 8080:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - 8003:8001
    volumes:
      - ./redisinsight:/db
    depends_on:
      - redis

  data-viewer:
    build: ./lehc-data-viewer
    depends_on:
      - mongo
    restart: always
    ports:
      - 8082:8888

  # reader1:
  #   build: ./lehc-reader

networks:
  default:
    name: lednet